FROM seitk/pipeline-eks

RUN curl -LO https://github.com/hairyhenderson/gomplate/releases/download/v3.6.0/gomplate_linux-amd64-slim \ 
    && chmod +x ./gomplate_linux-amd64-slim && mv ./gomplate_linux-amd64-slim /bin/gomplate